version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  allow:
    - dependency-type: "production"
  reviewers:
  - alyant34
  - KramerJeff
  - ksalmon
