export type AccountError = {
    error_code: string;
    error_name: string;
    error_description: string;
};
export type CustodialAccount = {
    /**
     * - A unique identifier generated by Rize
     */
    uid: string;
    /**
     * - A unique identifier Client supplies. It should be given when creating a new resource and must be unique within the resource type. If the same value is given, no new resource will be created.
     */
    external_uid: string;
    /**
     * - A UID referring to the customer this Custodial Account belongs to
     */
    customer_uid: string;
    /**
     * - A UID referring to the pool this Custodial Account belongs to
     */
    pool_uid: Array<string>;
    /**
     * - A UID referring to the specific Program Service Offering for which this account was created. Nullable if asset.
     */
    program_service_offering_uid: string | null;
    /**
     * A value indicating the overall state of this Customer:
     * - ***dda*** - Are liability DDA accounts. Any asset movements in or out of the brick-and-mortar accounts will be journaled in the dda Custodial Accounts. Balances shown in the dda accounts are the balances the owner Customers have.
     * - ***dda_cash_external*** - Are asset accounts, representing external accounts. When ODFI transfers, initated by a Synthetic Transfer from or to external Synthetic Accounts, are settled, the dda_cash_external Custodial Accounts will be credited or debited.
     * - ***dda_cash_received*** - Are asset cash accounts. When RDFI transfers, initiated outside of Rize from or to Custodial Accounts, are settled, the dda_cash_received Custodial Accounts will be credited or debited.
     */
    type: 'dda' | 'dda_cash_external' | 'dda_cash_received';
    /**
     * - Liability or asset. Liability Custodial Accounts represent real accounts at Financial Institutions. Asset accounts are used for accounting purposes and may be generated by Rize during events such as new custodial account creations or new external account connections.
     */
    liability: boolean;
    /**
     * - A friendly name used to identify the account at the Custodial Partner.
     */
    name: string | null;
    /**
     * - The date and time when the Customer was locked. This field will be null if and only if the lock_reason is null.
     */
    primary_account: boolean;
    /**
     * A value indicating the overall state of this Custodial Account (nullable if account type is asset):
     * - ***active*** - The Custodial Account is opened and available for asset movement and balance inquiries.
     * - ***archived*** - The Custodial Account is archived. All archived Custodial Accounts will have a $0.00 balance. This generally occurs when a Customer is archived or leaves the Service Offering that requires this Custodial Account.
     */
    status: 'active' | 'archived' | 'good' | null;
    /**
     * - A list of errors related to this account. These are passed through during interactions with the underlying Custodial Partner and can help with resolving customer issues. Only provided for accounts that are in an error or manual_review status.
     */
    account_errors: Array<AccountError>;
    /**
     * - The current settled balance of this Custodial Account in US Dollars
     */
    net_usd_balance: string;
    /**
     * - The sum of all pending transactions for this Custodial Account in US Dollars
     */
    net_usd_pending_balance: string;
    /**
     * - The balance available to spend calculated as Normal balance less any withdrawals. Pending deposits are not included
     */
    net_usd_available_balance: string;
    /**
     * - The ACH account number that can be used to make transfers into/out of this account. Nullable if asset.
     */
    account_number: string | null;
    /**
     * - Last 4 digits of the ACH account number. Nullable if asset.
     */
    account_number_masked: string | null;
    /**
     * - The ABA routing number associated with the Custodial Partner. Nullable if asset.
     */
    routing_number: string | null;
    /**
     * - The DateTime at which this account was created
     */
    opened_at: Date;
    /**
     * - The DateTime at which this account was closed
     */
    closed_at: Date;
};
export type CustodialAccountListQuery = {
    /**
     * - Filter by Customer. Multiple values are allowed
     */
    customer_uid?: Array<string>;
    /**
     * - A unique, immutable id provided Clien
     */
    external_uid?: string;
    /**
     * -  Maximum number of items to retrieve. This filter is automatically applied with the default value if not given. Default: 100
     */
    limit?: string;
    /**
     * - Index of the items to start retrieving from. Default: 0
     */
    offset?: string;
    /**
     * - Filter by liability or asset
     */
    liability?: string;
    /**
     * - Filter by type. Multiple values are allowed.
     */
    type?: Array<string>;
};
