export type KYCDocument = {
    /**
     * - A unique identifier generated by Rize.
     */
    uid: string;
    /**
     * - The KYC document type.
     */
    type: 'contract' | 'license' | 'other' | 'passport' | 'utility';
    /**
     * - The name of this file, exclusive of any extension.
     */
    filename: string;
    /**
     * - A note describing the document.
     */
    note: string;
    /**
     * - The filename extension.
     */
    extension: string;
    created_at: string;
};
