export type Product = {
    /**
     * - A unique identifier generated by Rize
     */
    uid: string;
    /**
     * - A unique name to identify the resource
     */
    name: string;
    description: string;
    /**
     * - A unique identifier for a Compliance Plan
     */
    product_compliance_plan_uid: string;
    /**
     * - Name for a Compliance Plan
     */
    compliance_plan_name: string;
    /**
     * - A list of uids referring to Products that must be onboarded before this one
     */
    prerequisite_product_uids: array<string>;
    /**
     * - A list of Profile Requirements a Customer must provide Profile Responses to
     */
    profile_requirements: array<ProfileRequirement>;
    /**
     * - A uid referring to the program.
     */
    program_uid: string;
};
export type ProfileRequirement = {
    /**
     * - A UID referring to the Profile Requirement
     */
    profile_requirement_uid: string;
    /**
     * - A statement that requires response in order to onboard a Customer for a Product
     */
    profile_requirement: string;
    /**
     * - A list of accepted responses from the customer
     */
    response_values: array<string>;
    /**
     * - an indication of whether a response is required or optional
     */
    required: boolean;
};
export type ProductListQuery = {
    /**
     * - Filter by Program.
     */
    program_uid?: string;
    /**
     * - Maximum number of items to retrieve. This filter is automatically applied with the default value if not given. Default = 100.
     */
    limit?: number;
    /**
     * - Index of the items to start retrieving from. Default = 0.
     */
    offset?: number;
};
