export type SyntheticAccountType = {
    /**
     * - A unique identifier generated by Rize
     */
    uid: string;
    /**
     * - A unique name to identify the resource
     */
    name: string;
    /**
     * - The name of the Synthetic Account Category for this type. Accounts can be in one of several categories that indicate their handling properties and defining characteristics such as 'general' or 'external'. As an example, 'external' accounts do not actually hold any assets and are instead used to represent an account at an external institution for use in initiating transfers.
     */
    synthetic_account_category: 'general' | 'external' | 'plaid_external';
    /**
     * - A description outlining the intended use and requirements for this program's instance of the synthetic_account_type
     */
    description: string;
    /**
     * - A uid referring to the Program this synthetic_account_type belongs to
     */
    program_uid?: string;
};
export type SyntheticAccountTypeListQuery = {
    /**
     * - Only list Synthetic Account Types that are available to be used by the given Program
     */
    program_uid?: string;
    /**
     * - Maximum number of items to retrieve. This filter is automatically applied with the default value if not given. Default: 100
     */
    limit?: number;
    /**
     * - Index of the items to start retrieving from. Default: 0
     */
    offset?: number;
};
export type SyntheticAccount = {
    /**
     * - A unique identifier generated by Rize
     */
    uid: string;
    /**
     * - A unique identifier Client supplies. It should be given when creating a new resource and must be unique within the resource type. If the same value is given, no new resource will be created.
     */
    external_uid: string;
    /**
     * - A unique name to identify the resource.
     */
    name: string;
    /**
     * - A UID referring to the pool this Synthetic Account belongs to.
     */
    pool_uid: string;
    /**
     * - A UID referring to the Synthetic Account Type this Synthetic Account should be created as.
     */
    synthetic_account_type_uid: string;
    /**
     * - The name of the Synthetic Account Category associated with the Synthetic Account Type for this account. Refer to the Synthetic Account Type for details.
     */
    synthetic_account_category: 'general' | 'external' | 'plaid_external';
    /**
     * A value indicating the overall state of this account:
     * - ***initiated*** - The Synthetic Account is being set up and is not usable. Currently this status is only applicable to the `plaid_external` category. A `plaid_external` Synthetic Account will have the `initiated` status when created. The status will be updated to `active` when the setup is complete.
     * - ***active*** - The Synthetic Account is available for Customers to interact with. The Synthetic Account can be used in Transfers and transaction and balance inquiries.
     * - ***archived*** - The Synthetic Account is no longer available. Archived Synthetic Accounts will have a balance of $0.00.
     * - ***failed*** - The Synthetic Account setup has failed. Currently the `failed` status is only applicable to the `plaid_external` Synthetic Account category. Synthetic Accounts will start in the `initiated` status before transitioning to the `failed` status. Rize will not retry setting up Synthetic Accounts in the `failed` status and will treat them as inactive.
     */
    status: 'initiated' | 'active' | 'archived' | 'failed';
    /**
     * - Liability or asset. Any Synthetic Account created via POST /synthetic_accounts is a liability account, except for external accounts. Some asset Synthetic Accounts are automatically created by Rize during Customer onboarding for accounting purposes.
     */
    liability: boolean;
    /**
     * - The current settled balance of this account in US Dollars. This field will be null for synthetic_account_types in the external category.
     */
    net_usd_balance: string;
    /**
     * - The sum of all pending transactions for this account in US Dollars. This field will be null for Synthetic Account Types in the external category.
     */
    net_usd_pending_balance: string;
    /**
     * - The balance available to spend calculated as the settled balance less any pending withdrawals Pending deposits are not included. This field will be null for Synthetic Account Types in the external category.
     */
    net_usd_available_balance: string;
    /**
     * - Used to identify the Master Synthetic Accounts that exist for every Program Customer. Master Synthetic Accounts are the default accounts where any unknown custodial transactions will settle and cannot be archived while a Program Customer is still active.
     */
    master_account: boolean;
    /**
     * - The ACH account number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `external` category will require an `account_number`. Submitting an `account_number` with a Synthetic Account Type that does not require one will result in the account number being ignored.
     */
    account_number: string | null;
    /**
     * - Last 4 digits of the ACH account number.
     */
    account_number_last_four: string | null;
    /**
     * - The ABA routing number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `external` category will require a `routing_number`. Submitting a `routing_number` with a Synthetic Account Type that does not require one will result in the routing number being ignored.
     */
    routing_number: string | null;
    /**
     * - The DateTime at which this account was created
     */
    opened_at: string;
    /**
     * - The DateTime at which this account was closed. This value will be present if the status is `archived` or `failed`.
     */
    closed_at: string | null;
    /**
     * - A UID referring to the Synthetic Account where the funds in this account were transferred when closed. Any transactions issued against this account after it is closed will instead go to the `closed_to` account
     */
    closed_to_synthetic_account_uid: string | null;
};
export type SyntheticAccountListQuery = {
    /**
     * - Filter by Customer. Multiple string values are allowed.
     */
    customer_uid?: Array<string>;
    /**
     * - A unique, immutable id provided Client
     */
    external_uid?: string;
    /**
     * - Filter by pool. Multiple string values are allowed.
     */
    pool_uid?: Array<string>;
    /**
     * - Maximum number of items to retrieve. This filter is automatically applied with the default value if not given. Default: 100
     */
    limit?: number;
    /**
     * - Index of the items to start retrieving from. Default: 0
     */
    offset?: number;
    /**
     * - Filter by Synthetic Account Type
     */
    synthetic_account_type_uid?: string;
    /**
     * - Filter by Synthetic Account Category
     */
    synthetic_account_category?: 'general' | 'external' | 'plaid_external';
    /**
     * - Filter by liability or asset
     */
    liability?: boolean;
    sort?: 'name_asc' | 'name_desc' | 'net_usd_balance_asc' | 'net_usd_balance_desc' | 'net_usd_pending_balance_asc' | 'net_usd_pending_balance_desc' | 'net_usd_available_balance_asc' | 'net_usd_available_balance_desc';
};
export type SyntheticAccountCreateOptions = {
    /**
     * - The ACH account number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `external` category will require an `account_number`. Submitting an `account_number` with a Synthetic Account Type that does not require one will result in the account number being ignored.
     */
    account_number?: string | null;
    /**
     * - The ABA routing number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `external` category will require a `routing_number`. Submitting a `routing_number` with a Synthetic Account Type that does not require one will result in the routing number being ignored.
     */
    routing_number?: string | null;
    /**
     * - The Rize processor token from Plaid. If a Synthetic Account Type from the category `plaid_external` is provided, `plaid_processor_token` must also be provided. Submitting a `plaid_processor_token` with any other Synthetic Account Type will result in the token being ignored.
     */
    plaid_processor_token?: string | null;
};
