export type Transfer = {
    /**
     * - A unique identifier generated by Rize.
     */
    uid: string;
    /**
     * - A unique identifier Client supplies. It should be given when creating a new resource and must be unique within the resource type. If the same value is given, no new resource will be created.
     */
    external_uid: string;
    /**
     * - Synthetic Account to pull asset from. Must be an active liability or external-type account. Cannot be equal to `destination_synthetic_account_uid`.
     */
    source_synthetic_account_uid: string;
    /**
     * - Synthetic Account where the asset should land. Must be an active liability or external-type account. Cannot be equal to `source_synthetic_account_uid`.
     */
    destination_synthetic_account_uid: string;
    /**
     * The customer connected to the source Synthetic Account.
     */
    initiating_customer_uid: string;
    /**
     * The customer connected to the destination Synthetic Account.
     */
    destination_customer_uid: string;
    /**
     * - The USD amount to transfer
     */
    usd_transfer_amount: string;
    /**
     * A value indicating the overall status of the Transfer:
     * - ***queued*** - Transfers begin in the Queued status. Queued indicates that Rize has received a valid Transfer request and is preparing the Transfer.
     * - ***pending*** - Transfers move from a status of Queued to a status of Pending. A Pending status indicates that Rize has begun the movement of funds to complete the Transfer.
     * - ***settled*** - The Transfer is complete. The funds have been moved between the source and destination accounts.
     * - ***failed*** - The Transfer has failed. This may occur due to a system error, or problems with the origin and/or destination account. A new Transfer must be created to move the assets.
     */
    status: 'queued' | 'pending' | 'settled' | 'failed';
    created_at: string;
};
export type TransferListQuery = {
    /**
     * - Filter by Customer. Multiple values are allowed.
     */
    customer_uid?: Array<string>;
    /**
     * - A unique, immutable id provided Client.
     */
    external_uid?: string;
    /**
     * - Filter by pool. Multiple values are allowed.
     */
    pool_uid?: Array<string>;
    /**
     * - Filter by Synthetic Account. Multiple values are allowed.
     */
    synthetic_account_uid?: Array<string>;
    /**
     * - Maximum number of items to retrieve. This filter is automatically applied with the default value if not given. Default = 100.
     */
    limit?: number;
    /**
     * - Index of the items to start retrieving from. Default = 0.
     */
    offset?: number;
};
