
version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:4
    container_name: verdaccio_root_path
    ports:
      - '80:4873'
    volumes:
      - verdaccio:/verdaccio

volumes:
  verdaccio:
    driver: local